version: "3.9"

services:
  metrics-dashboard:
    build: .
    container_name: metrics-dashboard
    ports:
      - "8080:80"   # container 80 → host 8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 5s